from datetime import time as dt_time

START_TIME = dt_time(7, 0)
END_TIME = dt_time(10, 0)

LOW_FREQUENCY = 60
MID_FREQUENCY = 30
HIGH_FREQUENCY = 5

MEDIAN_TEMPERATURE = 23
MEDIAN_HUMIDITY = 35
STD_TEMPERATURE = 1
STD_HUMIDITY = 5
