from datetime import time as dt_time

START_TIME = dt_time(7, 0)
END_TIME = dt_time(10, 0)

LOW_FREQUENCY = 60
MID_FREQUENCY = 30
HIGH_FREQUENCY = 5

MEDIAN_TEMPERATURE = 25.5
MEDIAN_HUMIDITY = 52
STD_TEMPERATURE = 0.5
STD_HUMIDITY = 2